### ISSUE TITLE
width mistake in the UART16550 driver

### ISSUE THREAD

**Issue by NeutrinoLiu** [riscv-software-src/riscv-pk#151]
For the [uart16550](https://github.com/riscv/riscv-pk/blob/97b683ed3cbeeb059e5ad3de8f884db734447d56/machine/uart16550.c#L7) who holds the base of uart16550; it should be defined as a 32 bits pointer (aka uint32_t*), instead of 8bits pointer.

In your initialization func [uart16550_done](https://github.com/riscv/riscv-pk/blob/97b683ed3cbeeb059e5ad3de8f884db734447d56/machine/uart16550.c#L49), using array to visit the register with step of [0/1/2/3] requires a pointer with consistent width.

The reg address spec can be found in [axiuart16550 spec](https://www.xilinx.com/support/documentation/ip_documentation/axi_uart16550/v2_0/pg143-axi-uart16550.pdf) at page 12.

**Comment by ipatix** [comment]
Xilinx' UART16550A does not follow the classic ns16550a byte wise register layout.
I've created a PR some time ago which fixed this as long as the register width is specified in the device tree:
https://github.com/riscv/riscv-pk/pull/171

So I guess this issue can probably be closed.
