### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by liaolin1997** [riscv-software-src/riscv-pk#253]
Hello， I have set the RISCV varaiable, and executed
 ./configure --prefix=$RISCV --host=riscv64-unknown-elf
When I executed the make command, it falied and showed error.And I have no idea of the solution:

riscv64-unknown-elf-gcc -Wl,--build-id=none -nostartfiles -nostdlib -static    -fno-stack-protector -o dummy_payload dummy_payload.o -L.  -ldummy_payload -lgcc -Wl,--defsym=MEM_START=0x80000000,-T,./dummy_payload/dummy_payload.lds
/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: cannot open output file dummy_payload: Is a directory
collect2: error: ld returned 1 exit status
Makefile:336: recipe for target 'dummy_payload' failed
make: *** [dummy_payload] Error 1

**Comment by hakkattack** [comment]
I'm running into the same issue. Looks like the Makefile is broken. dummy_payload or pk cannot be build because there is a directory with conflicting name in the build directory.

**Comment by aswaterman** [comment]
Create a `build` directory and configure inside of that, rather than running configure inside of the repo's root.
