### ISSUE TITLE
Build pk using different spec extension versions?

### ISSUE THREAD

**Issue by Sharanabasavaexaleap** [riscv-software-src/riscv-pk#257]
hello, 
can we build pk using new spec extension versions for RISCV 32?
like example:
RV32I ,v2.1
M extension, v2.0
A extension, v2.1
F extension, v2.2
D extension, v2.2
C extension, v2.0

If it is possible, command to pass in configure?

**Comment by aswaterman** [comment]
pk doesn't even know about the concept of ISA version numbers, so hopefully the answer is "yes, you can, it'll probably just work".  But we can't offer support.
