### ISSUE TITLE
Proxy Kernel for Spike: Require Help

### ISSUE THREAD

**Issue by WajahatRiaz** [riscv-software-src/riscv-pk#270]
I'm trying to install proxy kernel for spike (RISC V software).
Firstly, I used 
`git clone https://github.com/riscv-software-src/riscv-pk.git pk-demo`
followed by
`../configure --prefix=$/home/whitebeard/riscv-demo --host=riscv64-unknown-elf`
then
`sudo make install`

The error I get is as follows: (screenshot attached for your perusal)
![Screenshot (4)](https://user-images.githubusercontent.com/61377755/155040768-0536bf16-2d1d-4aad-8dab-f73fcb6cffac.png)

I have tried deleting the folders and doing the proces over again. Still ended up with the same issue. 
I'm following the directions given in this video : [https://www.youtube.com/watch?v=zZUtTplVHwE](url)

**Comment by aswaterman** [comment]
See #204

**Comment by WajahatRiaz** [comment]
> See #204 
Yes I looked into it. Still didn't solve anything. Perhaps I'm making a mistake. Can you elaborate how the problem solved for you.

**Comment by saad-waheed** [comment]
@WajahatRiaz can you please send the output log when you execute the `.\configure ...` command?

**Comment by WajahatRiaz** [comment]
@saad-waheed Well the git repository I was using had bugs. I cloned the individual packages sperately in a folder and built them. It solved the issue. You have to add the path in the environment as well using the export command.

**Comment by saad-waheed** [comment]
Great 👍
