### ISSUE TITLE
Issue related to Proxy Kernel 

### ISSUE THREAD

**Issue by WajahatRiaz** [riscv-software-src/riscv-pk#271]
So I'm able to generate a.out file from by running the basic hello.c file using command `riscv32-unknown-elf-gcc hello.c`
After When I'm running the following command 
` /home/whitebeard/RISCV/riscv-pk/build/pk a.out`
but it prints the following error on my terminal
`-bash: /home/whitebeard/RISCV/riscv-pk/build/pk: cannot execute binary file: Exec format error`
Can someone tell me how can I resolve the issue?
@aswaterman can you guide please?

**Comment by aswaterman** [comment]
pk is a RISC-V binary, and it appears that you’re trying to directly
execute it on a non-RISC-V machine. Try running it on Spike.
