### ISSUE TITLE
toplevel inline-asm in pk/pk.c is broken

### ISSUE THREAD

**Issue by apinski-cavium** [riscv-software-src/riscv-pk#282]
I just happen to find this issue really (I was reading the code at random).
Basically the toplevel inline-asm in riscv-pk/pk/pk.c around line 185 does not set the section and reset the section back so the symbol rest_of_boot_loader might be in a random section (might even be in a debug section in some cases; e.g. gcc with -g3).

**Comment by aswaterman** [comment]
Fun that it has been working by coincidence.
