### ISSUE TITLE
spike pk hello, failed with assertion failed: !(eh.e_flags & EF_RISCV_RVC)

### ISSUE THREAD

**Issue by jundijiujieke** [riscv-software-src/riscv-pk#297]
spike pk hello, failed with assertion failed: !(eh.e_flags & EF_RISCV_RVC)
Does any know how to fix this probelm? I don't know whether is my riscv-tool's problem or pk's problem?

bbl loader
../pk/elf.c:47: assertion failed: !(eh.e_flags & EF_RISCV_RVC)
Power off

**Comment by aswaterman** [comment]
Looks like `pk` was compiled without support for the C extension, but you're trying to run a binary that requires the C extension.

**Comment by jundijiujieke** [comment]
> Looks like `pk` was compiled without support for the C extension, but you're trying to run a binary that requires the C extension.

Thanks for your reply, do you mean i have to reinstall the pk with C extension.

**Comment by aswaterman** [comment]
Yeah, I think building `pk` with support for the C extension will fix this issue.

**Comment by jundijiujieke** [comment]
Thanks for your help, I tried your solution and fixed this problem.

**Comment by aswaterman** [comment]
Great! Glad I was able to help.
