### ISSUE TITLE
Issue with linux

### ISSUE THREAD

**Issue by lforche** [riscv-software-src/riscv-pk#323]
I have gotten riscv64-unknown-linux-gnu to install and work. It will compile a small test file. I have riscv-isa-sim setup, but then I am trying to make the riscv-pk, and it throws this error:

gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks -fno-PIE    -DBBL_LOGO_FILE=\"bbl_logo_file\" -DMEM_START=0x80000000 -fno-stack-protector -U_FORTIFY_SOURCE -DBBL_PAYLOAD=\"bbl_payload\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/file.c
gcc: error: unrecognized argument in option ‘-mcmodel=medany’
gcc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
make: *** [Makefile:336: file.o] Error 1

I changed the medany to large, and then it threw this error:

gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=large -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks -fno-PIE    -DBBL_LOGO_FILE=\"bbl_logo_file\" -DMEM_START=0x80000000 -fno-stack-protector -U_FORTIFY_SOURCE -DBBL_PAYLOAD=\"bbl_payload\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/file.c
../pk/file.c: Assembler messages:
../pk/file.c:28: Error: no such instruction: `fence'
../pk/file.c:28: Error: no such instruction: `fence'
../pk/file.c:28: Error: no such instruction: `fence'
../pk/file.c:28: Error: no such instruction: `fence'

I used sudo ../configure --prefix=$RISCV --host=riscv64-unknown-linux-gnu to do the configure and sudo make to run before getting those errors.

Any ideas?

**Comment by aswaterman** [comment]
See https://github.com/riscv-software-src/riscv-pk/issues/204
