### ISSUE TITLE
Support RVC program without requiring RVC pk

### ISSUE THREAD

**Issue by caizixian** [riscv-software-src/riscv-pk#326]
A relevant issue is #297 

Is there any reason to not support loading RVC ELF when the kernel is compiled with RVC? I'm guessing that as long as the underlying hart supports RVC, we should be able to load RVC binaries.

**Comment by aswaterman** [comment]
The trapping and emulation code is tailored to the implementation’s ISA. We have no plans to change this: things work fine (better, actually) if you compile pk for the actual hardware ISA. I recommend dealing with the inconvenience rather than trying to change it.
