### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by MarcoBonino** [riscv-software-src/riscv-pk#336]
From the last 2 commits (47a2e87ccd4e95f80f0754c6f3312ccb3b90d916, 7f3bef01193137e3227fcf88bece86f5234b9bc5) the build is broken.

In addition I think the README should be updated.
Until commit 1a52fa44aba49307137ea2ad5263613da33a877b I was able to build using the following:
```
../configure --prefix=$RISCV --host=riscv64-unknown-elf --with-arch=rv64imafdc_zifencei
make
```

Now with make I get the following compilation error:
```
riscv64-unknown-elf-ranlib libutil.a
riscv64-unknown-elf-gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks -fno-PIE  -march=rv64imafdc_zifencei -mabi=lp64 -DBBL_LOGO_FILE=\"bbl_logo_file\" -DMEM_START=0x80000000 -fno-stack-protector -U_FORTIFY_SOURCE -DBBL_PAYLOAD=\"bbl_payload\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/pk.c
../pk/pk.c: Assembler messages:
../pk/pk.c:122: Error: unknown CSR `ssp'
make: *** [pk.o] Error 1
```

**Comment by aswaterman** [comment]
We started requiring a newer version of the assembler.  But we can avoid that extra dependence with a minor tweak, so we'll do so.
